version: 3

vars:
  overlay_basemap_image: maptiler/tileserver-gl
  api_image: ghcr.io/wikunia/essapi.jl/ess-api:jump-off
  tilemaker_image: ghcr.io/wikunia/essapi.jl/ess-tilemaker:jump-off

tasks:
  network:create:
    status:
      - test "$(docker network ls -q -f name=ess-network)"
    cmds:
      - docker network create ess-network --driver bridge

  images:pull:
    cmds:
      - docker pull {{.overlay_basemap_image}}
      - docker pull {{.api_image}}
      - docker pull {{.tilemaker_image}}

  basemap:restart:
    cmds:
      - task: images:pull
      - cmd: docker stop ess-basemap
        ignore_error: true
      - cmd: docker rm ess-basemap
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-basemap \
          --publish 8080:8080 \
          --restart unless-stopped \
          --volume /home/ole/ess/data/overlay:/data \
          {{.overlay_basemap_image}} \
          -c basemap-config.json

  overlay:restart:
    cmds:
      - task: images:pull
      - cmd: docker stop ess-overlay
        ignore_error: true
      - cmd: docker rm ess-overlay
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-overlay \
          --publish 8081:8080 \
          --restart unless-stopped \
          --volume /home/ole/ess/data/overlay:/data \
          {{.overlay_basemap_image}} \
          -c overlay-config.json

  api:restart:
    cmds:
      - task: images:pull
      - cmd: docker stop ess-api
        ignore_error: true
      - cmd: docker rm ess-api
        ignore_error: true
      - >
        docker run \
          --detach \
          --env-file "/home/ole/ess/env/.api" \
          --name ess-api \
          --publish 8000:8000 \
          --restart unless-stopped \
          --volume /home/ole/ess/data/api:/data \
          {{.api_image}}

  tilemaker:execute:
    vars:
      TILEMAKER_INPUT: '{{.TILEMAKER_INPUT | default ""}}'
      TILEMAKER_OUTPUT: '{{.TILEMAKER_OUTPUT | default ""}}'
    cmds:
      - task: images:pull
      - cmd: docker stop ess-tilemaker
        ignore_error: true
      - cmd: docker rm ess-tilemaker
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-tilemaker \
          --volume /home/ole/ess/data/api:/data:/data \
          {{.tilemaker_image}} \
          --input {{.TILEMAKER_INPUT}} \
          --output {{.TILEMAKER_OUTPUT}}

  ess:start:all:
    cmds:
      - task: network:create
      - task: basemap:restart
      - task: overlay:restart
      - task: api:restart

  docker:logs:
    cmds:
      - docker ps -q | xargs -L 1 docker logs --tail=0 --follow --timestamps
