version: '3'

vars:
  overlay_basemap_image: maptiler/tileserver-gl
  api_image: ghcr.io/wikunia/essapi.jl:jump-off

tasks:
  network:create:
    status:
      - test "$(docker network ls -q -f name=ess-network)"
    cmds:
      - docker network create ess-network --driver bridge

  images:pull:
    cmds:
      - docker pull {{.overlay_basemap_image}}
      - docker pull {{.api_image}}

  basemap:restart:
    deps: [images:pull]
    cmds:
      - cmd: docker stop ess-basemap
        ignore_error: true
      - cmd: docker rm ess-basemap
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-basemap \
          --publish 8080:8080 \
          --volume /home/ole/ess/data/overlay:/data \
          {{.overlay_basemap_image}} \
          -c basemap-config.json

  overlay:restart:
    deps: [images:pull]
    cmds:
      - cmd: docker stop ess-overlay
        ignore_error: true
      - cmd: docker rm ess-overlay
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-overlay \
          --publish 8081:8080 \
          --volume /home/ole/ess/data/overlay:/data \
          {{.overlay_basemap_image}} \
          -c overlay-config.json

  api:restart:
    deps: [images:pull]
    cmds:
      - cmd: docker stop ess-api
        ignore_error: true
      - cmd: docker rm ess-api
        ignore_error: true
      - >
        docker run \
          --detach \
          --env-file "/home/ole/ess/env/.api" \
          --name ess-api \
          --publish 8000:8000 \
          --volume /home/ole/ess/data/api:/data \
          {{.api_image}}
