version: '3'

tasks:
  network:create:
    status:
      - test "$(docker network ls -q -f name=ess-network)"
    cmds:
      - docker network create ess-network --driver bridge

  basemap:restart:
    cmds:
      - cmd: docker stop ess-basemap
        ignore_error: true
      - cmd: docker rm ess-basemap
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-basemap \
          --publish 8080:8080 \
          --volume /home/ole/ess/data/overlay:/data \
          maptiler/tileserver-gl \
          -c basemap-config.json

  overlay:restart:
    cmds:
      - cmd: docker stop ess-overlay
        ignore_error: true
      - cmd: docker rm ess-overlay
        ignore_error: true
      - >
        docker run \
          --detach \
          --name ess-overlay \
          --publish 8081:8080 \
          --volume /home/ole/ess/data/overlay:/data \
          maptiler/tileserver-gl \
          -c overlay-config.json

  api:restart:
    cmds:
      - cmd: docker stop ess-api
        ignore_error: true
      - cmd: docker rm ess-api
        ignore_error: true
      - >
        docker run \
          --detach \
          --env-file "/home/ole/ess/env/.api" \
          --name ess-api \
          --publish 8000:8000 \
          --volume /home/ole/ess/data/api:/data \
          ghcr.io/wikunia/essapi.jl:jump-off
