---
name: 'Publish Docker Image'

on:
  push:
    branches:
      - main
      - jump-off
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: set up qemu
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: publish docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/wikunia/essapi.jl:${{ github.ref_name }}
