---
name: 'Publish Docker Image'

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main
      - jump-off
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: set up qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: arm64
      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/wikunia/essapi.jl/ess-api:${{ github.ref_name }}
